"""ARK/Palworld 詳細設定エディタの項目定義(旧GUIから共有化)。

ARK: (fk, section, key, type, ラベル, 既定値)  fk=gus|game
Pal: (key, type, ラベル, 既定値, choices)
"""

_ARK_GM = "/Script/ShooterGame.ShooterGameMode"
_SS = "ServerSettings"
_GSESS = "/Script/Engine.GameSession"

ARK_SETTINGS_TABS = [
    ("基本・倍率", [
        ("gus", _SS, "XPMultiplier", "float", "経験値(XP)倍率", "1.0"),
        ("gus", _SS, "TamingSpeedMultiplier", "float", "テイム速度倍率(大=速い)", "1.0"),
        ("gus", _SS, "HarvestAmountMultiplier", "float", "採取量倍率", "1.0"),
        ("gus", _SS, "HarvestHealthMultiplier", "float", "資源の耐久倍率(大=長持ち)", "1.0"),
        ("gus", _SS, "ResourcesRespawnPeriodMultiplier", "float", "資源リポップ間隔倍率(小=早い)", "1.0"),
        ("gus", _SS, "ItemStackSizeMultiplier", "float", "アイテムスタック倍率", "1.0"),
        ("gus", _SS, "DinoCountMultiplier", "float", "野生恐竜の数倍率", "1.0"),
        ("gus", _SS, "OverrideOfficialDifficulty", "float", "難易度上書き(5.0=野生最大Lv150)", "5.0"),
        ("gus", _SS, "DifficultyOffset", "float", "難易度オフセット(0〜1)", "1.0"),
        ("gus", _SS, "MaxTamedDinos", "int", "サーバー全体のテイム上限数", "5000"),
        ("game", _ARK_GM, "MaxNumberOfPlayersInTribe", "int", "トライブ最大人数(0=無制限)", "0"),
    ]),
    ("時間・環境", [
        ("gus", _SS, "DayCycleSpeedScale", "float", "1日の進行速度倍率", "1.0"),
        ("gus", _SS, "DayTimeSpeedScale", "float", "昼の長さ倍率", "1.0"),
        ("gus", _SS, "NightTimeSpeedScale", "float", "夜の長さ倍率", "1.0"),
        ("gus", _SS, "GlobalSpoilingTimeMultiplier", "float", "食料の腐敗時間倍率(大=腐りにくい)", "1.0"),
        ("gus", _SS, "GlobalItemDecompositionTimeMultiplier", "float", "ドロップ品の消滅時間倍率", "1.0"),
        ("gus", _SS, "GlobalCorpseDecompositionTimeMultiplier", "float", "死体の消滅時間倍率", "1.0"),
        ("game", _ARK_GM, "CropGrowthSpeedMultiplier", "float", "作物の成長速度倍率", "1.0"),
        ("game", _ARK_GM, "CropDecaySpeedMultiplier", "float", "作物の枯れ速度倍率", "1.0"),
        ("game", _ARK_GM, "PoopIntervalMultiplier", "float", "排泄間隔倍率", "1.0"),
        ("game", _ARK_GM, "LayEggIntervalMultiplier", "float", "採卵間隔倍率", "1.0"),
        ("game", _ARK_GM, "HairGrowthSpeedMultiplier", "float", "毛/ヒゲの伸び速度倍率", "1.0"),
    ]),
    ("プレイヤー", [
        ("gus", _SS, "PlayerCharacterFoodDrainMultiplier", "float", "空腹の減り倍率", "1.0"),
        ("gus", _SS, "PlayerCharacterWaterDrainMultiplier", "float", "水分の減り倍率", "1.0"),
        ("gus", _SS, "PlayerCharacterStaminaDrainMultiplier", "float", "スタミナの減り倍率", "1.0"),
        ("gus", _SS, "PlayerCharacterHealthRecoveryMultiplier", "float", "体力回復倍率", "1.0"),
        ("gus", _SS, "PlayerDamageMultiplier", "float", "プレイヤー与ダメ倍率", "1.0"),
        ("gus", _SS, "PlayerResistanceMultiplier", "float", "プレイヤー被ダメ倍率(小=硬い)", "1.0"),
        ("gus", _SS, "OxygenSwimSpeedStatMultiplier", "float", "酸素→泳速の倍率", "1.0"),
        ("game", _ARK_GM, "OverrideMaxExperiencePointsPlayer", "int", "プレイヤー最大経験値(空=既定)", ""),
    ]),
    ("恐竜", [
        ("gus", _SS, "DinoCharacterFoodDrainMultiplier", "float", "恐竜の空腹の減り倍率", "1.0"),
        ("gus", _SS, "DinoCharacterStaminaDrainMultiplier", "float", "恐竜のスタミナ減り倍率", "1.0"),
        ("gus", _SS, "DinoCharacterHealthRecoveryMultiplier", "float", "恐竜の体力回復倍率", "1.0"),
        ("gus", _SS, "DinoDamageMultiplier", "float", "野生恐竜の与ダメ倍率", "1.0"),
        ("gus", _SS, "DinoResistanceMultiplier", "float", "野生恐竜の被ダメ倍率(小=硬い)", "1.0"),
        ("gus", _SS, "TamedDinoDamageMultiplier", "float", "テイム恐竜の与ダメ倍率", "1.0"),
        ("gus", _SS, "TamedDinoResistanceMultiplier", "float", "テイム恐竜の被ダメ倍率(小=硬い)", "1.0"),
        ("gus", _SS, "AllowFlyerCarryPvE", "bool", "飛行生物で他生物を掴む(PvE)", "False"),
        ("gus", _SS, "AllowRaidDinoFeeding", "bool", "タイタノ等の餌付けテイムを許可", "False"),
        ("gus", _SS, "MaxTamedDinos_SoftTameLimit", "int", "テイム軟上限(超過分は消去対象)", "5000"),
    ]),
    ("繁殖", [
        ("game", _ARK_GM, "MatingIntervalMultiplier", "float", "交配クールダウン倍率(小=再交配が早い)", "1.0"),
        ("game", _ARK_GM, "MatingSpeedMultiplier", "float", "発情までの速度倍率(大=速い)", "1.0"),
        ("game", _ARK_GM, "EggHatchSpeedMultiplier", "float", "卵の孵化速度倍率(大=速い)", "1.0"),
        ("game", _ARK_GM, "BabyMatureSpeedMultiplier", "float", "赤ちゃん成長速度倍率(大=速い)", "1.0"),
        ("game", _ARK_GM, "BabyFoodConsumptionSpeedMultiplier", "float", "赤ちゃんの餌消費倍率(小=省エネ)", "1.0"),
        ("game", _ARK_GM, "BabyCuddleIntervalMultiplier", "float", "刷り込み間隔倍率(小=刷り込み頻度↓)", "1.0"),
        ("game", _ARK_GM, "BabyCuddleGracePeriodMultiplier", "float", "刷り込み猶予時間倍率", "1.0"),
        ("game", _ARK_GM, "BabyImprintAmountMultiplier", "float", "刷り込み1回あたりの量倍率", "1.0"),
        ("game", _ARK_GM, "BabyImprintingStatScaleMultiplier", "float", "刷り込みによるステ上昇倍率", "1.0"),
        ("gus", _SS, "AllowAnyoneBabyImprintCuddle", "bool", "刷り込みを誰でも行える", "False"),
    ]),
    ("構造物", [
        ("gus", _SS, "StructureDamageMultiplier", "float", "建築物の与ダメ倍率", "1.0"),
        ("gus", _SS, "StructureResistanceMultiplier", "float", "建築物の被ダメ倍率(小=頑丈)", "1.0"),
        ("gus", _SS, "PvEStructureDecayPeriodMultiplier", "float", "PvE建築の崩壊猶予倍率(大=長持ち)", "1.0"),
        ("gus", _SS, "DisableStructureDecayPvE", "bool", "PvE建築の自動崩壊を無効化", "False"),
        ("gus", _SS, "TheMaxStructuresInRange", "int", "一定範囲内の最大建築数", "10500"),
        ("gus", _SS, "AlwaysAllowStructurePickup", "bool", "建築物をいつでも回収可能", "False"),
        ("gus", _SS, "StructurePickupTimeAfterPlacement", "float", "設置後に回収できる秒数", "30"),
        ("gus", _SS, "StructurePickupHoldDuration", "float", "回収の長押し秒数", "0.5"),
        ("gus", _SS, "PerPlatformMaxStructuresMultiplier", "float", "プラットフォーム上の建築上限倍率", "1.0"),
        ("gus", _SS, "AllowCaveBuildingPvE", "bool", "洞窟内の建築を許可(PvE)", "False"),
    ]),
    ("ルール・PvP/PvE", [
        ("gus", _SS, "serverPVE", "bool", "PvEモード(ON=PvPなし・恐竜同士戦わない)", "False"),
        ("gus", _SS, "ServerHardcore", "bool", "ハードコア(死亡でLv1に)", "False"),
        ("gus", _SS, "ServerCrosshair", "bool", "照準(クロスヘア)表示", "False"),
        ("gus", _SS, "ServerForceNoHUD", "bool", "HUDを強制非表示", "False"),
        ("gus", _SS, "ShowMapPlayerLocation", "bool", "マップに自分の位置を表示", "False"),
        ("gus", _SS, "ShowFloatingDamageText", "bool", "ダメージ数値を表示", "False"),
        ("gus", _SS, "AllowThirdPersonPlayer", "bool", "三人称視点を許可", "True"),
        ("gus", _SS, "EnablePVPGamma", "bool", "PvPでガンマ調整を許可", "False"),
        ("gus", _SS, "DisableFriendlyFire", "bool", "同トライブへの誤射を無効化", "False"),
        ("gus", _SS, "GlobalVoiceChat", "bool", "全体ボイスチャット", "False"),
        ("gus", _SS, "ProximityChat", "bool", "近接チャットのみ", "False"),
        ("gus", _SS, "AllowHitMarkers", "bool", "ヒットマーカー表示", "True"),
        ("gus", _SS, "KickIdlePlayersPeriod", "int", "放置キックまでの秒数", "3600"),
        ("gus", _SS, "TribeNameChangeCooldown", "int", "トライブ名変更のクールダウン(分)", "15"),
        ("gus", _SS, "AutoSavePeriodMinutes", "float", "オートセーブ間隔(分)", "15"),
        ("gus", _GSESS, "MaxPlayers", "int", "最大プレイヤー数", "70"),
    ]),
    ("クライオポッド", [
        # ASAで低温ポッドは「起動中のクライオ冷蔵庫の近く」でしか出せない仕様。以下で緩和できる。
        ("gus", _SS, "DisableCryopodFridgeRequirement", "bool",
         "冷蔵庫なしでポッドを出せる(ONで冷蔵庫不要)", "False"),
        ("gus", _SS, "DisableCryopodEnemyCheck", "bool",
         "敵/構造物チェックを無視して出せる", "False"),
        ("gus", _SS, "AllowCryoFridgeOnSaddle", "bool",
         "サドル/イカダにクライオ冷蔵庫を設置可", "False"),
        ("gus", _SS, "EnableCryopodNerf", "bool",
         "ポッドから出した直後のデバフを有効化", "True"),
        ("gus", _SS, "CryopodNerfDuration", "int", "デバフの継続時間(秒)", "10"),
        ("gus", _SS, "CryopodNerfIncomingDamageMultPercent", "float",
         "デバフ中の被ダメージ倍率(例0.25)", "0.25"),
        ("gus", _SS, "EnableCryoSicknessPVE", "bool",
         "PvEでもクライオ酔いを有効化", "False"),
    ]),
    ("転送・クラスタ", [
        # クラスタ本体(clusterid/ClusterDirOverride)は各マップの launch_args で設定済み。
        # ここはマップ間のアップロード/ダウンロード(転送)を細かく制御する項目。
        ("gus", _SS, "NoTributeDownloads", "bool",
         "転送のダウンロードを全面禁止(ONで持ち込み不可)", "False"),
        ("gus", _SS, "PreventDownloadSurvivors", "bool", "キャラのダウンロードを禁止", "False"),
        ("gus", _SS, "PreventDownloadItems", "bool", "アイテムのダウンロードを禁止", "False"),
        ("gus", _SS, "PreventDownloadDinos", "bool", "恐竜のダウンロードを禁止", "False"),
        ("gus", _SS, "PreventUploadSurvivors", "bool", "キャラのアップロードを禁止", "False"),
        ("gus", _SS, "PreventUploadItems", "bool", "アイテムのアップロードを禁止", "False"),
        ("gus", _SS, "PreventUploadDinos", "bool", "恐竜のアップロードを禁止", "False"),
        ("gus", _SS, "CrossARKAllowForeignDinoDownloads", "bool",
         "他クラスタの恐竜ダウンロードを許可", "False"),
        ("gus", _SS, "TributeItemExpirationSeconds", "int",
         "アップロードしたアイテムの保持秒数(既定86400=24h)", "86400"),
        ("gus", _SS, "TributeDinoExpirationSeconds", "int",
         "アップロードした恐竜の保持秒数", "86400"),
        ("gus", _SS, "TributeCharacterExpirationSeconds", "int",
         "アップロードしたキャラの保持秒数", "86400"),
    ]),
]

_PAL_DEATH = [("None", "なし(ドロップしない)"), ("Item", "アイテムのみ"),
              ("ItemAndEquipment", "アイテム＋装備"), ("All", "全部(パル含む)")]
PAL_SETTINGS_TABS = [
    ("倍率(QoL)", [
        ("ExpRate", "float", "経験値倍率", "1.0", None),
        ("PalCaptureRate", "float", "パル捕獲率(大=捕まえやすい)", "1.0", None),
        ("PalSpawnNumRate", "float", "パルの出現数倍率", "1.0", None),
        ("CollectionDropRate", "float", "採取量倍率", "1.0", None),
        ("CollectionObjectRespawnSpeedRate", "float", "採取物の再出現速度(小=速い)", "1.0", None),
        ("EnemyDropItemRate", "float", "敵ドロップ倍率", "1.0", None),
        ("WorkSpeedRate", "float", "パルの作業速度倍率", "1.0", None),
        ("PalEggDefaultHatchingTime", "float", "卵の孵化時間(時間・短=速い)", "72.0", None),
    ]),
    ("生活・時間", [
        ("PlayerStomachDecreaceRate", "float", "プレイヤー空腹の減り(小=減りにくい)", "1.0", None),
        ("PalStomachDecreaceRate", "float", "パルの空腹の減り", "1.0", None),
        ("PlayerStaminaDecreaceRate", "float", "スタミナの減り", "1.0", None),
        ("PlayerAutoHPRegeneRate", "float", "自動HP回復倍率", "1.0", None),
        ("DayTimeSpeedRate", "float", "昼の進行速度", "1.0", None),
        ("NightTimeSpeedRate", "float", "夜の進行速度", "1.0", None),
        ("BuildObjectDamageRate", "float", "建築物の被ダメ倍率", "1.0", None),
        ("BuildObjectDeteriorationDamageRate", "float", "建築物の劣化速度(0=劣化なし)", "1.0", None),
    ]),
    ("難易度・ルール", [
        ("PalDamageRateAttack", "float", "パルの与ダメ倍率", "1.0", None),
        ("PalDamageRateDefense", "float", "パルの被ダメ倍率(小=硬い)", "1.0", None),
        ("PlayerDamageRateAttack", "float", "プレイヤーの与ダメ倍率", "1.0", None),
        ("PlayerDamageRateDefense", "float", "プレイヤーの被ダメ倍率(小=硬い)", "1.0", None),
        ("DeathPenalty", "choice", "死亡ペナルティ", "Item", _PAL_DEATH),
        ("bEnablePlayerToPlayerDamage", "bool", "PvP(プレイヤー間ダメージ)", "False", None),
        ("bEnableFriendlyFire", "bool", "フレンドリーファイア", "False", None),
        ("bHardcore", "bool", "ハードコア(死亡でキャラロスト)", "False", None),
        ("bEnableFastTravel", "bool", "ファストトラベル許可", "True", None),
    ]),
    ("拠点・ギルド", [
        ("BaseCampWorkerMaxNum", "int", "拠点のパル最大数", "15", None),
        ("BaseCampMaxNum", "int", "拠点の最大数", "128", None),
        ("GuildPlayerMaxNum", "int", "ギルド最大人数", "20", None),
        ("BaseCampMaxNumInGuild", "int", "ギルドの拠点最大数", "4", None),
        ("DropItemMaxNum", "int", "地面ドロップ最大数", "3000", None),
        ("bAllowGlobalPalboxExport", "bool", "グローバルパルボックス書出許可", "True", None),
        ("bAllowGlobalPalboxImport", "bool", "グローバルパルボックス取込許可", "False", None),
    ]),
    ("サーバー", [
        ("ServerName", "str", "サーバー名", "", None),
        ("ServerDescription", "str", "サーバー説明", "", None),
        ("ServerPlayerMaxNum", "int", "最大プレイヤー数", "32", None),
        ("ServerPassword", "str", "参加パスワード(空=なし)", "", None),
        ("bIsPvP", "bool", "PvPモード", "False", None),
        ("bEnableInvaderEnemy", "bool", "襲撃イベントを有効", "True", None),
        ("SupplyDropSpan", "int", "サプライドロップ間隔(分)", "180", None),
    ]),
]


# ==== 2026-07-18 追加(ark.wiki.gg / Server_configuration 準拠) ====
# 実在キー + 定番の未収録設定を、セクション確定で追加。既存タブは触らず新タブで拡張する。
_GAME = _ARK_GM
ARK_SETTINGS_TABS += [
    ("経験値・レシピ", [
        ("game", _GAME, "HarvestXPMultiplier", "float", "採取XP倍率", "1.0"),
        ("game", _GAME, "CraftXPMultiplier", "float", "製作XP倍率", "1.0"),
        ("game", _GAME, "GenericXPMultiplier", "float", "汎用XP倍率(移動/発見等)", "1.0"),
        ("game", _GAME, "KillXPMultiplier", "float", "討伐XP倍率", "1.0"),
        ("game", _GAME, "SpecialXPMultiplier", "float", "特殊XP倍率(ボス等)", "1.0"),
        ("game", _GAME, "CustomRecipeEffectivenessMultiplier", "float", "カスタムレシピ効果倍率", "1.0"),
        ("game", _GAME, "CustomRecipeSkillMultiplier", "float", "カスタムレシピの製作スキル寄与倍率", "1.0"),
        ("game", _GAME, "bAllowUnlimitedRespecs", "bool", "マインドワイプ無制限(24時間CDを無視)", "False"),
        ("game", _GAME, "bAllowSpeedLeveling", "bool", "移動速度へのステ振りを許可", "False"),
        ("game", _GAME, "bAutoUnlockAllEngrams", "bool", "全エングラムを自動解放", "False"),
        ("game", _GAME, "bOnlyAllowSpecifiedEngrams", "bool", "指定エングラムのみ習得可(配列で指定)", "False"),
    ]),
    ("PvP・レイド保護", [
        ("gus", _SS, "PreventOfflinePvP", "bool", "オフラインレイド防止(ORP)を有効化", "False"),
        ("gus", _SS, "PreventOfflinePvPInterval", "float", "ORP発動までの猶予(秒)", "900.0"),
        ("gus", _SS, "bPvEAllowTribeWar", "bool", "PvEでトライブ戦争を許可", "True"),
        ("gus", _SS, "bPvEAllowTribeWarCancel", "bool", "宣戦布告の取り消しを許可", "False"),
        ("gus", _SS, "bAutoPvETimer", "bool", "時間帯でPvP/PvEを自動切替", "False"),
        ("gus", _SS, "bAutoPvEUseSystemTime", "bool", "自動PvEに実時間を使う(OFF=ゲーム内時間)", "False"),
        ("gus", _SS, "AutoPvEStartTimeSeconds", "int", "PvE開始時刻(0〜86399秒)", "0"),
        ("gus", _SS, "AutoPvEStopTimeSeconds", "int", "PvE終了時刻(0〜86399秒)", "0"),
        ("gus", _SS, "bIncreasePvPRespawnInterval", "bool", "連続死でリスポーン待ちを増やす", "True"),
        ("gus", _SS, "IncreasePvPRespawnIntervalBaseAmount", "float", "追加リスポーン待ちの基本秒", "60.0"),
        ("gus", _SS, "IncreasePvPRespawnIntervalMultiplier", "float", "追加リスポーン待ちの倍率", "2.0"),
        ("gus", _SS, "IncreasePvPRespawnIntervalCheckPeriod", "float", "連続死とみなす期間(秒)", "300.0"),
    ]),
    ("追加ルール・その他", [
        ("gus", _SS, "bUseSingleplayerSettings", "bool", "シングルプレイ設定を使う(SP準拠の緩いレート一括)", "False"),
        ("game", _GAME, "MaxDifficulty", "bool", "最大難易度を強制(Game.ini)", "False"),
        ("gus", _SS, "MaxPersonalTamedDinos", "int", "1トライブのテイム上限(0=無制限)", "0"),
        ("gus", _SS, "DestroyTamesOverLevelClamp", "int", "この値を超えるテイムを消去(0=無効)", "0"),
        ("gus", _SS, "MaxTributeItems", "int", "アップロード可能アイテム数の上限", "50"),
        ("gus", _SS, "MaxTributeDinos", "int", "アップロード可能恐竜数の上限", "20"),
        ("gus", _SS, "ClampResourceHarvestDamage", "bool", "資源への採取ダメージを上限で制限", "False"),
        ("gus", _SS, "ClampItemStats", "bool", "アイテムのステ上限クランプを有効化", "False"),
        ("gus", _SS, "UseCorpseLocator", "bool", "死亡地点にビーコン表示", "True"),
        ("gus", _SS, "PreventDiseases", "bool", "病気(沼熱等)を無効化", "False"),
        ("gus", _SS, "NonPermanentDiseases", "bool", "病気を非永続にする(死亡で治る)", "False"),
        ("gus", _SS, "PreventSpawnAnimations", "bool", "リスポーン時の起き上がりモーション省略", "False"),
        ("gus", _SS, "PreventMateBoost", "bool", "交配ブースト(そばで攻撃UP)を無効化", "False"),
        ("gus", _SS, "AllowFlyingStaminaRecovery", "bool", "飛行生物の上でスタミナ回復", "False"),
        ("gus", _SS, "AdminLogging", "bool", "管理者コマンドをチャットに記録", "False"),
        ("gus", _SS, "AllowHideDamageSourceFromLogs", "bool", "ダメージ元をトライブログで隠す", "False"),
        ("gus", _SS, "SupplyCrateLootQualityMultiplier", "float", "補給物資の品質倍率", "1.0"),
        ("gus", _SS, "FishingLootQualityMultiplier", "float", "釣りの品質倍率", "1.0"),
        ("gus", _SS, "ImplantSuicideCD", "float", "インプラント自殺のCD(秒)", "3600.0"),
        ("gus", _SS, "StartTimeHour", "float", "ワールド開始時刻(時・-1=無効)", "-1.0"),
    ]),
    ("恐竜・構造(追加)", [
        ("gus", _SS, "RaidDinoCharacterFoodDrainMultiplier", "float", "レイド恐竜(タイタノ等)の空腹減り倍率", "1.0"),
        ("gus", _SS, "bForceCanRideFliers", "bool", "飛行生物の騎乗を強制許可(マップ問わず)", "False"),
        ("gus", _SS, "DisableImprintDinoBuff", "bool", "刷り込み者ボーナスを無効化", "False"),
        ("game", _GAME, "PassiveTameIntervalMultiplier", "float", "受動テイムの間隔倍率", "1.0"),
        ("game", _GAME, "BabyImprinterQualityMultiplier", "float", "刷り込み品質倍率", "1.0"),
        ("game", _GAME, "bPassiveDefensesDamageRiderlessDinos", "bool", "パッシブ防衛が騎乗なし恐竜に効く", "False"),
        ("gus", _SS, "bDisableStructurePlacementCollision", "bool", "地形貫通で建築を許可", "False"),
        ("gus", _SS, "AllowMultipleAttachedC4", "bool", "1体に複数C4を設置可", "False"),
        ("gus", _SS, "AllowCaveBuildingPvP", "bool", "洞窟建築を許可(PvP)", "False"),
        ("gus", _SS, "AllowCrateSpawnsOnTopOfStructures", "bool", "建築の上に補給物資を湧かせる", "False"),
        ("gus", _SS, "OverrideStructurePlatformPrevention", "bool", "プラットフォーム上の設置制限を解除", "False"),
        ("gus", _SS, "AutoDestroyOldStructuresMultiplier", "float", "古い建築の自動破壊倍率(0=無効)", "0.0"),
        ("gus", _SS, "StructurePreventResourceRadiusMultiplier", "float", "建築が資源湧きを止める範囲倍率", "1.0"),
    ]),
]
